name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Build
      run: |
        make

    - uses: actions/upload-artifact@v4
      with:
        name: libhvee-binaries (${{ matrix.os }})
        path: bin/
